import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CartesianGrid, ComposedChart, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, BarChart3, CalendarClock, Gauge, Users } from 'lucide-react'
import { api } from '../services/api'
import { useUI } from '../state'
import { PageHeader } from '../components/PageHeader'
import { HistoryChart } from '../components/HistoryChart'
import { StatusBadge } from '../components/StatusBadge'
import { EmptyState } from '../components/EmptyState'

const pts=['SD-01','SD-02','SD-03','SD-04'];const lineColors=['#c76b35','#36739e','#588867','#786e9b']
export function AnalyticsPage(){
 const id=useUI(s=>s.selectedInspectionId);const currentPoint=useUI(s=>s.selectedPoint);const setPoint=useUI(s=>s.setPoint);const [onlyPoint,setOnlyPoint]=useState(currentPoint)
 const histories=useQuery({queryKey:['all-point-histories'],queryFn:async()=>Object.fromEntries(await Promise.all(pts.map(async p=>[p,await api.pointHistory(p)])))})
 const events=useQuery({queryKey:['maintenance-events'],queryFn:api.events});const inspectors=useQuery({queryKey:['inspectors'],queryFn:api.inspectors});const qa=useQuery({queryKey:['qa-summary'],queryFn:api.qa});const summary=useQuery({queryKey:['maintenance-summary'],queryFn:api.maintenanceSummary})
 const allHistories=histories.data||{} as Record<string,any[]>;const active=allHistories[onlyPoint]||[]
 const transformed=useMemo(()=>active.map((r:any)=>({...r,margin_to_caution_mm:r.length_mm===null?null:r.caution_mm-r.length_mm,margin_to_danger_mm:r.length_mm===null?null:r.danger_mm-r.length_mm,maintenance_action:r.maintenance_action||'',maintenance_priority:r.maintenance_priority||null,maintenance_event_at_date:r.maintenance_event_at_date})),[active])
 const normalized=useMemo(()=>{const byDate=new Map<string,any>();pts.forEach(p=>(allHistories[p]||[]).forEach((r:any)=>{if(!byDate.has(r.date))byDate.set(r.date,{date:r.date,x:new Date(r.date).getTime()});byDate.get(r.date)[p]=r.length_mm===null?null:r.length_mm/r.danger_mm}));return [...byDate.values()]},[allHistories])
 const inspectorCounts=useMemo(()=>{const m=new Map<string,number>();(inspectors.data||[]).forEach((x:any)=>m.set(x.inspector,(m.get(x.inspector)||0)+1));return [...m.entries()].map(([inspector,count])=>({inspector,count}))},[inspectors.data])
 const qTemporal=qa.data?.temporal;const inspectorTimeline=inspectors.data||[]
 return <>
  <PageHeader eyebrow="HISTORICAL DATA · NO FORECASTING" title="Crack analytics" description="Measurements remain discrete RAW observations. NULLs, repair boundaries and negative deltas remain visible." action={<label className="select-control"><span>FOCUS POINT</span><select value={onlyPoint} onChange={e=>{setOnlyPoint(e.target.value);setPoint(e.target.value)}}>{pts.map(p=><option key={p}>{p}</option>)}</select></label>}/>
  <div className="analytics-callout"><Activity size={16}/><span>Measurement tolerance: <b>±10 mm</b> for interval change interpretation only. Structural state uses RAW length and official limits, unaffected by tolerance.</span><span className="historical-pill">VALIDATED QA OUTPUTS</span></div>
  <section className="panel chart-panel analytics-primary"><div className="panel-heading"><div><span className="eyebrow">RAW MEASUREMENTS · OFFICIAL THRESHOLDS</span><h2>{onlyPoint} · Length by inspection date</h2></div><div className="chart-legend-inline"><span><i className="legend-caution"/>Caution</span><span><i className="legend-danger"/>Danger</span><span><i className="legend-null"/>N/I</span></div></div>{transformed.length?<HistoryChart data={transformed} point={onlyPoint} mode="length" events={events.data||[]}/>:<EmptyState/>}<div className="chart-caption">No smoothing or interpolation · RAW measurement markers · repair dates shown as vertical lines</div></section>
  <div className="analytics-chart-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">OPERATING LIFE</span><h2>Length vs accumulated hours</h2></div><Gauge size={16}/></div><HistoryChart data={transformed} point={onlyPoint} mode="length" axis="hours" events={events.data||[]} compact/><div className="chart-caption">X = operating hours · Y = RAW length (mm)</div></section>
   <section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">THRESHOLD MARGIN</span><h2>Margin to Caution & Danger</h2></div><span className="unit-note">mm</span></div><div className="margin-plot"><ResponsiveContainer width="100%" height={235}><LineChart data={transformed.map((d:any)=>({...d,x:new Date(d.date).getTime()}))} margin={{top:10,right:18,bottom:5,left:0}}><CartesianGrid stroke="#e8edf1" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="x" type="number" domain={['dataMin','dataMax']} scale="time" tickFormatter={v=>new Date(v).toLocaleDateString('es-CO',{month:'short',year:'2-digit'})} tick={{fontSize:10,fill:'#7b8793'}} axisLine={false} tickLine={false}/><YAxis unit=" mm" tick={{fontSize:10,fill:'#7b8793'}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>new Date(Number(v)).toLocaleDateString('es-CO')} formatter={(v:any,n:any)=>[v===null?'N/I':`${Number(v).toFixed(1)} mm`,n]}/><Legend/><Line dataKey="margin_to_caution_mm" name="Margin to Caution" stroke="#d59d23" connectNulls={false} dot={{r:2}} isAnimationActive={false}/><Line dataKey="margin_to_danger_mm" name="Margin to Danger" stroke="#c84238" connectNulls={false} dot={{r:2}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="chart-caption">Negative margin means RAW length is above the corresponding threshold.</div></section>
   <section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">CHANGE CLASSIFICATION</span><h2>Effective ΔL by inspection</h2></div><span className="unit-note">mm</span></div><HistoryChart data={transformed} point={onlyPoint} mode="delta" events={events.data||[]} compact/><div className="change-legend"><span><i className="legend-stable"/>Within ±10 mm → 0</span><span><i className="legend-growth"/>Significant growth</span><span><i className="legend-decrease"/>Significant decrease review</span><span><i className="legend-reset"/>Maintenance reset</span></div></section>
   <section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">APPARENT RATE</span><h2>Effective growth rate</h2></div><span className="unit-note">mm / 1000 h</span></div><HistoryChart data={transformed} point={onlyPoint} mode="growth" events={events.data||[]} compact/><div className="chart-caption">Rates are excluded through NULL and maintenance. Negative values are review flags, not physical negative crack growth.</div></section>
  </div>
  <div className="analytics-chart-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">NORMALIZED CONDITION</span><h2>Severity ratio · all four points</h2></div><span className="unit-note">L RAW / Danger</span></div><ResponsiveContainer width="100%" height={265}><LineChart data={normalized} margin={{top:10,right:20,bottom:6,left:0}}><CartesianGrid stroke="#e8edf1" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="x" type="number" scale="time" domain={['dataMin','dataMax']} tickFormatter={v=>new Date(v).toLocaleDateString('es-CO',{month:'short',year:'2-digit'})} tick={{fontSize:10,fill:'#7b8793'}} axisLine={false} tickLine={false}/><YAxis unit=" ×" tick={{fontSize:10,fill:'#7b8793'}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>new Date(Number(v)).toLocaleDateString('es-CO')} formatter={(v:any,n:any)=>[v===null?'N/I':Number(v).toFixed(3),n]}/><Legend/>{pts.map((p,i)=><Line key={p} dataKey={p} connectNulls={false} stroke={lineColors[i]} strokeWidth={1.8} dot={{r:2}} activeDot={{r:4}} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer><div className="chart-caption">Same normalized value means same fraction of that point’s own Danger limit. No interpolation across NULL.</div></section>
   <section className="panel chart-panel cadence-panel"><div className="panel-heading"><div><span className="eyebrow">INSPECTION CADENCE · OBSERVED</span><h2>Inspection interval distribution</h2></div><CalendarClock size={17}/></div><div className="cadence-stats">{[['Δdays',qTemporal?.delta_dias],['Δhours',qTemporal?.delta_horas]].map(([label,st]:any)=><div key={label}><span>{label} · n={st?.n}</span><strong>{st?.median?.toFixed(1)||'—'}<small> median</small></strong><div>mean {st?.mean?.toFixed(1)} · SD {st?.std?.toFixed(1)}</div><div>range {st?.min?.toFixed(1)} – {st?.max?.toFixed(1)} · IQR {st?.iqr?.toFixed(1)}</div></div>)}</div><div className="chart-caption">Statistics from the reproducible QA summary, not recomputed or rounded into schedule rules.</div></section>
  </div>
  <div className="analytics-lower-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">INSPECTOR DISTRIBUTION</span><h2>Inspection dates over time</h2></div><Users size={17}/></div><InspectorTimeline rows={inspectorTimeline}/></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">STRUCTURAL STATE</span><h2>{onlyPoint} · recorded history</h2></div><Activity size={17}/></div><div className="state-history-list">{active.map((r:any)=><div key={r.date}><time>{r.date}</time><StatusBadge state={r.structural_state}/><b>{r.length_mm===null?'N/I':`${r.length_mm} mm`}</b><span>{r.inspector}</span>{r.maintenance_event_at_date&&<em>Repair</em>}</div>)}</div></section></div>
  <div className="analytics-footnote"><b>Analysis boundary:</b> The data contain discrete crack-length measurements. They do not independently establish a physical crack propagation mechanism or inspector causality. Current views support condition review only; no forecasting is implemented.</div>
 </>
}
function InspectorTimeline({rows}:{rows:any[]}){const names=[...new Set(rows.map(x=>x.inspector))];const palette=['#356f9a','#d47b38','#6a8b70','#8175a2'];return <div className="inspector-timeline"><div className="inspector-track">{rows.map((r,i)=><div key={i} className="inspector-marker" title={`${r.date} · ${r.inspector}`} style={{left:`${rows.length>1?i/(rows.length-1)*100:0}%`,background:palette[names.indexOf(r.inspector)%palette.length]}}><span>{r.inspector.replace('INSP-','I')}</span></div>)}</div><div className="timeline-axis"><span>{rows[0]?.date}</span><span>{rows.at(-1)?.date}</span></div><div className="inspector-legend">{names.map((n,i)=><span key={n}><i style={{background:palette[i%palette.length]}}/>{n}<b>{rows.filter(x=>x.inspector===n).length}</b></span>)}</div></div>}
