import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Camera, FileText, Image, Upload, ExternalLink, ShieldCheck } from 'lucide-react'
import { api } from '../services/api'
import { STATIC_DEMO } from '../services/staticDemo'
import { useUI } from '../state'
import { PageHeader } from '../components/PageHeader'
import { EmptyState } from '../components/EmptyState'

export function EvidencePage(){
 const qc=useQueryClient();const notify=useUI(s=>s.notify);const selectedId=useUI(s=>s.selectedInspectionId)
 const [point,setPoint]=useState('SD-01');const [notes,setNotes]=useState('');const [file,setFile]=useState<File|null>(null)
 const [linkType,setLinkType]=useState<'inspection'|'work-order'>('inspection');const [inspectionId,setInspectionId]=useState<number|undefined>(selectedId);const [workOrderId,setWorkOrderId]=useState<number|undefined>()
 const list=useQuery({queryKey:['evidence'],queryFn:()=>api.evidence()});const inspections=useQuery({queryKey:['inspections','evidence'],queryFn:()=>api.inspections({limit:500})});const orders=useQuery({queryKey:['work-orders'],queryFn:()=>api.workOrders()})
 useEffect(()=>{if(inspectionId===undefined&&selectedId!==undefined)setInspectionId(selectedId)},[selectedId,inspectionId])
 const upload=useMutation({mutationFn:api.uploadEvidence,onSuccess:async()=>{await qc.invalidateQueries({queryKey:['evidence']});setFile(null);setNotes('');notify('success','Evidence uploaded and linked to the selected record.')},onError:e=>notify('error',e.message)})
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!file){notify('error','Choose a JPG, PNG, WEBP or PDF file.');return}const inspection=inspectionId??selectedId??inspections.data?.[0]?.id;if(linkType==='inspection'&&!inspection){notify('error','Choose an inspection record.');return}if(linkType==='work-order'&&!workOrderId){notify('error','Choose a work order.');return}const body=new FormData();body.append('file',file);body.append('point',point);body.append('notes',notes);if(linkType==='inspection')body.append('inspection_id',String(inspection));else body.append('work_order_id',String(workOrderId));upload.mutate(body)}
 return <>
  <PageHeader eyebrow="DOCUMENT CONTROL" title="Evidence library" description="Photographs and files explicitly uploaded by the user, linked to inspections or work orders. Historical image filenames remain metadata until the source file is available."/>
  <div className="evidence-banner"><ShieldCheck size={17}/><div><b>Provenance preserved</b><span>Historical workbook image references are treated as metadata, not as attached photographs. Uploaded evidence stays separate from the RAW workbook.</span></div></div>
  <div className="evidence-layout" style={STATIC_DEMO?{gridTemplateColumns:'1fr'}:undefined}><section className="panel evidence-upload-panel" style={STATIC_DEMO?{display:'none'}:undefined}><div className="panel-heading"><div><span className="eyebrow">ADD EVIDENCE</span><h2>Upload inspection proof</h2></div><Camera size={18}/></div><form onSubmit={submit}>
   <label className="evidence-drop"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="upload-icon"><Upload size={21}/></div><b>{file?.name||'Select an image or PDF'}</b><span>JPG · PNG · WEBP · PDF · maximum 20 MB</span><small>La evidencia se conserva en el almacenamiento configurado para esta instalación.</small></label>
   <label className="modal-label">Link to<select value={linkType} onChange={e=>setLinkType(e.target.value as 'inspection'|'work-order')}><option value="inspection">Inspection</option><option value="work-order">Work order</option></select></label>
   {linkType==='inspection'?<><label className="modal-label">Inspection date<select required value={inspectionId??selectedId??inspections.data?.[0]?.id??''} onChange={e=>setInspectionId(Number(e.target.value))}>{(inspections.data||[]).map(i=><option key={i.id} value={i.id}>{i.date} · #{i.id} · {i.imported?'historical':'new'}</option>)}</select></label><label className="modal-label">Inspection point<select value={point} onChange={e=>setPoint(e.target.value)}>{['SD-01','SD-02','SD-03','SD-04'].map(p=><option key={p}>{p}</option>)}</select></label></>:<label className="modal-label">Work order<select required value={workOrderId??''} onChange={e=>setWorkOrderId(Number(e.target.value))}><option value="">Select work order</option>{(orders.data||[]).map(o=><option key={o.id} value={o.id}>WO-{String(o.id).padStart(4,'0')} · {o.point} · {o.status}</option>)}</select></label>}
   <label className="modal-label">Context<textarea rows={3} placeholder="Describe the evidence source and inspection context" value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button button-primary full-width" disabled={upload.isPending||!file}><Upload size={15}/>{upload.isPending?'Uploading…':'Upload and link evidence'}</button><div className="upload-disclaimer">Files are stored separately; adding evidence never edits the historical Excel source.</div>
  </form></section>
  <section className="panel evidence-list-panel"><div className="panel-heading"><div><span className="eyebrow">LOCAL ARCHIVE</span><h2>Uploaded evidence</h2></div><span className="point-count">{list.data?.length??0}</span></div>{!list.data?.length?<EmptyState title="No uploaded evidence yet" description={STATIC_DEMO?'Las fotos históricas no fueron entregadas; las referencias se conservan como metadatos.':'Historical image references are not shown as files. Upload verified evidence to attach it to a record.'}/>:<div className="evidence-grid">{list.data.map(e=><article key={e.id} className="evidence-card">{e.media_type.startsWith('image/')?<img src={api.evidenceUrl(e.id)} alt={e.filename}/>:<div className="evidence-file"><FileText size={34}/><span>PDF DOCUMENT</span></div>}<div><b>{e.filename}</b><span>{e.point||'General'} · {new Date(e.uploaded_at).toLocaleDateString('es-CO')}</span>{e.notes&&<p>{e.notes}</p>}<a href={api.evidenceUrl(e.id)} target="_blank" rel="noreferrer">Open file <ExternalLink size={12}/></a></div></article>)}</div>}</section></div>
  <section className="panel evidence-metadata-panel"><div className="panel-heading"><div><span className="eyebrow">SOURCE FILE REFERENCES</span><h2>Historical image metadata</h2></div><Image size={18}/></div><div className="metadata-list">{['EH4_SD_tijeras_spindle.png'].map(f=><div key={f}><FileText size={15}/><b>{f}</b><span>Referenced in workbook · physical attachment is not bundled in the validated dataset</span><i>METADATA ONLY</i></div>)}</div></section>
 </>
}
