import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Search, ChevronDown, ChevronUp, FileClock, Filter, AlertTriangle, Save, Eye, X, Camera, ArrowRight } from 'lucide-react'
import { api } from '../services/api'
import { useUI } from '../state'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { EmptyState } from '../components/EmptyState'
import { stateSlug, type Inspection, type Measurement } from '../types'

const POINTS=['SD-01','SD-02','SD-03','SD-04']
export function InspectionsPage(){
 const [showForm,setShowForm]=useState(false);const [query,setQuery]=useState('');const [selected,setSelected]=useState<Inspection|null>(null)
 const inspections=useQuery({queryKey:['inspections'],queryFn:()=>api.inspections({limit:500})})
 const qc=useQueryClient();const notify=useUI(s=>s.notify);const setInspection=useUI(s=>s.setInspection)
 const rows=useMemo(()=>inspections.data?.filter(i=>!query||`${i.date} ${i.inspector} ${i.measurements.map(m=>m.point).join(' ')}`.toLowerCase().includes(query.toLowerCase()))||[],[inspections.data,query])
 return <>
  <PageHeader eyebrow="INSPECTION REGISTER" title="Inspections" description="Registro histórico y nuevas campañas de inspección · Los históricos importados son inmutables." action={<button className="button button-primary" onClick={()=>setShowForm(true)}><Plus size={16}/> New inspection</button>}/>
  <div className="inspections-summary"><div><FileClock size={17}/><span><b>{inspections.data?.length??'—'}</b> inspection dates</span></div><div><span>Fuente histórica:</span><b>25 fechas · 100 puntos</b></div><div className="summary-note"><AlertTriangle size={15}/> 3 registros históricos N/I preservados como NULL</div></div>
  <section className="panel table-panel"><div className="table-toolbar"><div><b>Inspection history</b><span>Ordenado por fecha descendente · una fila por campaña</span></div><label className="table-search"><Search size={15}/><input placeholder="Filter date or inspector" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="filter-chip"><Filter size={14}/> All points <ChevronDown size={13}/></button></div>
   {inspections.isLoading?<div className="page-loading small"><span className="loader-ring"/> Loading inspections…</div>:rows.length===0?<EmptyState title="No matching inspections"/>:<div className="table-scroll"><table><thead><tr><th>INSPECTION DATE</th><th>HOUR METER</th><th>INSPECTOR</th><th>COMPLETENESS</th><th>CONDITION</th><th>POINT READINGS</th><th></th></tr></thead><tbody>{rows.map(i=>{const cnt={normal:i.measurements.filter(m=>m.structural_state==='Normal').length,alert:i.measurements.filter(m=>m.structural_state==='Alerta').length,critical:i.measurements.filter(m=>m.structural_state==='Crítico').length,ni:i.measurements.filter(m=>m.structural_state==='N/I').length};return <tr key={i.id} onClick={()=>{setSelected(i);setInspection(i.id)}}><td><b>{i.date}</b>{i.maintenance_event&&<span className="repair-tag">Documented repair</span>}</td><td>{i.hours.toLocaleString('es-CO')} h</td><td><span className="inspector-chip">{i.inspector}</span></td><td><div className="table-completeness"><span>{((4-cnt.ni)/4*100).toFixed(0)}%</span><i><b style={{width:`${(4-cnt.ni)/4*100}%`}}/></i></div></td><td><div className="state-counts"><i className="legend-normal"/>{cnt.normal}<i className="legend-alert"/>{cnt.alert}<i className="legend-critical"/>{cnt.critical}<i className="legend-incomplete"/>{cnt.ni}</div></td><td><div className="reading-chips">{i.measurements.map(m=><span key={m.point} title={`${m.point}: ${m.structural_state}`} className={`reading-chip reading-${stateSlug(m.structural_state)}`}>{m.point.replace('SD-','')}: {m.length_mm===null?'N/I':`${m.length_mm} mm`}</span>)}</div></td><td><button className="icon-button" title="Open inspection details" onClick={e=>{e.stopPropagation();setSelected(i);setInspection(i.id)}}><Eye size={15}/></button></td></tr>})}</tbody></table></div>}
  </section>
  {showForm&&<NewInspectionModal onClose={()=>setShowForm(false)} onSaved={async(id)=>{setShowForm(false);setInspection(id);await qc.invalidateQueries();notify('success','Inspección guardada. El RAW histórico permanece sin cambios.')}}/>}
  {selected&&<InspectionDrawer inspection={selected} onClose={()=>setSelected(null)}/>}
 </>
}
function NewInspectionModal({onClose,onSaved}:{onClose:()=>void;onSaved:(id:number)=>void}){
 const qc=useQueryClient();const notify=useUI(s=>s.notify);const rows=useQuery({queryKey:['inspections','new-form'],queryFn:()=>api.inspections({limit:500})})
 const last=rows.data?.[0]
 const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [hours,setHours]=useState(last?.hours?String(last.hours):'');const [inspector,setInspector]=useState('');const [values,setValues]=useState<Record<string,string>>({'SD-01':'','SD-02':'','SD-03':'','SD-04':''});const [missing,setMissing]=useState<Record<string,boolean>>({'SD-01':false,'SD-02':false,'SD-03':false,'SD-04':false});const [comments,setComments]=useState<Record<string,string>>({});const [error,setError]=useState('')
 const mutation=useMutation({mutationFn:api.createInspection,onSuccess:(r)=>onSaved(r.id),onError:e=>setError(e.message)})
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError('');const blank=POINTS.find(p=>!missing[p]&&values[p].trim()==='');if(blank){setError(`Enter a measured length or mark ${blank} as N/I. Blank fields are never converted to 0.`);return}const measures=POINTS.map(point=>({point,length_mm:missing[point]?null:Number(values[point]),comment:comments[point]||null}));mutation.mutate({equipment:'EH4-01',date,hours:Number(hours),inspector,measurements:measures})}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal-card inspection-modal"><div className="modal-head"><div><span className="eyebrow">INSPECTION ENTRY</span><h2>Register a new inspection</h2><p>All four points are required; mark N/I explicitly when not measured.</p></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div>
  <form onSubmit={submit}><div className="form-grid"><label>Inspection date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Hour meter (h)<input required min="0" step="0.1" type="number" value={hours} onChange={e=>setHours(e.target.value)}/><small>Last recorded: {last?.hours.toLocaleString('es-CO')??'—'} h</small></label><label className="form-wide">Inspector name / ID<input required maxLength={80} placeholder="e.g. INSP-04" value={inspector} onChange={e=>setInspector(e.target.value)}/></label></div>
   <div className="form-section-label"><span>MEASUREMENTS</span><small>0 mm ≠ NULL / N/I</small></div>
   <div className="measurement-form-list">{POINTS.map((p,i)=><div className={`measurement-form-row ${missing[p]?'is-missing':''}`} key={p}><div className="measurement-label"><b>{p}</b><span>{['Metal base de tijeras, lado derecho','Metal base de tijeras, lado izquierdo','Spindle delantero, lado derecho','Spindle delantero, lado izquierdo'][i]}</span></div><label className="number-field"><input type="number" min="0" step="0.1" disabled={missing[p]} required={!missing[p]} value={values[p]} placeholder="0.0" onChange={e=>setValues(v=>({...v,[p]:e.target.value}))}/><span>mm</span></label><label className="ni-check"><input type="checkbox" checked={missing[p]} onChange={e=>setMissing(v=>({...v,[p]:e.target.checked}))}/> N/I</label><input className="comment-input" placeholder="Comment (optional)" value={comments[p]||''} onChange={e=>setComments(v=>({...v,[p]:e.target.value}))}/></div>)}</div>
   {error&&<div className="form-error"><AlertTriangle size={15}/>{error}</div>}<div className="modal-actions"><span><Camera size={14}/> Add photos after saving from Evidence.</span><button type="button" className="button button-ghost" onClick={onClose}>Cancel</button><button type="submit" className="button button-primary" disabled={mutation.isPending}><Save size={15}/>{mutation.isPending?'Saving…':'Save inspection'}</button></div>
  </form>
 </div></div>
}
function InspectionDrawer({inspection,onClose}:{inspection:Inspection;onClose:()=>void}){const setId=useUI(s=>s.setInspection);return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="detail-drawer"><div className="drawer-head"><div><span className="eyebrow">INSPECTION RECORD · {inspection.imported?'VALIDATED HISTORICAL':'NEW RECORD'}</span><h2>{inspection.date}</h2><p>{inspection.hours.toLocaleString('es-CO')} h · {inspection.inspector}</p></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="drawer-section"><h3>Four point readings</h3>{inspection.measurements.map(m=><MeasurementDetail key={m.point} m={m}/>)}</div><div className="drawer-section"><h3>Provenance</h3><div className="provenance-card"><b>{inspection.imported?'Imported from validated QA outputs':'Created in this application'}</b><span>{inspection.zone}</span><span>Equipment: {inspection.equipment}</span><span>{inspection.measurements.some(m=>m.source_row)?`Excel source rows: ${inspection.measurements.map(m=>m.source_row).filter(Boolean).join(', ')}`:'No original Excel row; this is an appended record.'}</span></div></div><button className="button button-primary full-width" onClick={()=>{setId(inspection.id);onClose()}}>Show in dashboard <ArrowRight size={15}/></button></aside></div>}
function MeasurementDetail({m}:{m:Measurement}){return <div className="drawer-measurement"><div><b>{m.point}</b><span>{m.description}</span><small>{m.comment||'No comment in source record.'}</small>{m.image_file&&<small className="source-image">Image metadata: {m.image_file} · physical file availability not verified</small>}</div><div><strong>{m.length_mm===null?'N/I':`${m.length_mm} mm`}</strong><StatusBadge state={m.structural_state}/></div></div>}
