import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, CalendarPlus, CheckCircle2, ClipboardCheck, FileWarning, Plus, Wrench } from 'lucide-react'
import { api } from '../services/api'
import { useUI } from '../state'
import type { Recommendation } from '../types'
import { PageHeader } from '../components/PageHeader'
import { PriorityBadge, StatusBadge } from '../components/StatusBadge'
import { EmptyState } from '../components/EmptyState'

function actionLabel(s:string){return (s||'').replaceAll('_',' ')}
export function MaintenancePage(){
 const navigate=useNavigate()
 const id=useUI(s=>s.selectedInspectionId);const selectedPoint=useUI(s=>s.selectedPoint);const setPoint=useUI(s=>s.setPoint);const notify=useUI(s=>s.notify);const qc=useQueryClient();const [draft,setDraft]=useState<Recommendation|null>(null)
 const recs=useQuery({queryKey:['recommendations',id],queryFn:()=>api.recommendations(id)})
 const orders=useQuery({queryKey:['work-orders'],queryFn:()=>api.workOrders()})
 const events=useQuery({queryKey:['maintenance-events'],queryFn:api.events})
 const rec=recs.data||[];const activeOrders=orders.data||[]
 const create=useMutation({mutationFn:api.createWorkOrder,onSuccess:async()=>{await qc.invalidateQueries();notify('success','Orden creada en estado PENDING. Requiere revisión y aprobación explícitas.');setDraft(null)},onError:e=>notify('error',e.message)})
 const ordersByMeasurement=new Set(activeOrders.map(o=>o.source_measurement_id).filter(Boolean))
 return <>
  <PageHeader eyebrow="DETERMINISTIC MAINTENANCE RULES" title="Maintenance recommendations" description="Acciones explicables calculadas desde la inspección seleccionada. Son apoyo a la decisión; no implican aval profesional ni sustituyen la aprobación humana de una orden."/>
  <div className="maintenance-banner"><ClipboardCheck size={18}/><div><b>Rule set V1 · deterministic</b><span>Structural state uses RAW length and official Caution/Danger. The 10 mm tolerance is only applied to changes between measurements. Rules are reproducible and do not imply engineer endorsement.</span></div><span className="historical-pill">NO PREDICTIVE MODELS</span></div>
  <div className="recommendation-cards">{rec.map(r=><article key={r.point} className={`recommendation-card ${r.structural_state==='Crítico'?'rec-critical':r.structural_state==='Alerta'?'rec-alert':r.structural_state==='N/I'?'rec-missing':'rec-normal'}`} onMouseEnter={()=>setPoint(r.point)}><div className="rec-card-top"><span>{r.point}</span><StatusBadge state={r.structural_state}/><PriorityBadge priority={r.priority}/></div><h2>{actionLabel(r.action)}</h2><p>{r.reason}</p><div className="rec-reading"><div><span>RAW LENGTH</span><b>{r.length_mm===null?'N/I':`${r.length_mm} mm`}</b></div><div><span>THRESHOLDS</span><b>{r.caution_mm} / {r.danger_mm} mm</b></div><div><span>MODE</span><b>{r.mode?.replaceAll('_',' ')||'Baseline'}</b></div></div>{r.data_warning&&<div className="warning-line"><FileWarning size={14}/>{r.data_warning.replaceAll('_', ' ')} · human review</div>}<div className="rec-card-bottom"><small>As of {r.date} · {r.hours.toLocaleString('es-CO')} h</small><button className="button button-primary button-small" onClick={()=>setDraft(r)} disabled={ordersByMeasurement.has(r.measurement_id)}>{ordersByMeasurement.has(r.measurement_id)?<><CheckCircle2 size={14}/> Order created</>:<><CalendarPlus size={14}/> Create work order</>}</button></div></article>)}</div>
  <div className="maintenance-lower"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">DOCUMENTED MAINTENANCE</span><h2>Source events</h2></div><Wrench size={17}/></div>{(events.data||[]).length?<div className="event-table">{events.data?.map(e=><div key={e.id}><time>{e.date}</time><b>{e.point}</b><span className="event-type-pill">{e.event_type}</span><p>“{e.comment}”</p><small>Row {e.source_row??'—'} · confidence {e.confidence} · {e.source}</small></div>)}</div>:<EmptyState title="No documented events"/>}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">REGISTERED WORK</span><h2>Open orders</h2></div><button className="text-button" onClick={()=>navigate('/planning')}>Open planner <ArrowRight size={14}/></button></div>{activeOrders.length?<div className="open-order-list">{activeOrders.slice(0,6).map(o=><div key={o.id}><span className="wo-number">WO-{String(o.id).padStart(4,'0')}</span><b>{o.point} · {o.intervention_type}</b><span className={`wo-status status-${o.status.toLowerCase()}`}>{o.status.replaceAll('_',' ')}</span><PriorityBadge priority={o.priority}/></div>)}</div>:<EmptyState title="No work orders yet" description="Create an order from a recommendation to start planning."/>}</section></div>
  {draft&&<div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><span className="eyebrow">CONVERT RECOMMENDATION</span><h2>Draft work order · {draft.point}</h2><p>Review first. The new order starts as PENDING and does not imply approval or execution.</p></div><button className="icon-button" onClick={()=>setDraft(null)}>×</button></div><div className="order-source-card"><StatusBadge state={draft.structural_state}/><b>{actionLabel(draft.action)}</b><PriorityBadge priority={draft.priority}/><p>{draft.reason}</p></div><label className="modal-label">Intervention / work scope<input id="intervention" defaultValue={draft.action.replaceAll('_',' ')} /></label><label className="modal-label">Description<textarea id="description" defaultValue={`${draft.reason}\n\nSource: ${draft.point}, ${draft.date}; ${draft.length_mm===null?'N/I':`${draft.length_mm} mm RAW`}.`} rows={4}/></label><div className="form-error note-blue"><CalendarPlus size={15}/> Choose a schedule date later in Planning. No date is invented here.</div><div className="modal-actions"><span>Created from measurement #{draft.measurement_id}</span><button className="button button-ghost" onClick={()=>setDraft(null)}>Cancel</button><button className="button button-primary" disabled={create.isPending} onClick={()=>{const intervention=(document.getElementById('intervention') as HTMLInputElement).value;const description=(document.getElementById('description') as HTMLTextAreaElement).value;if(!intervention.trim()||!description.trim()){notify('error','Intervention and description are required.');return}create.mutate({point:draft.point,priority:draft.priority||'P1',intervention_type:intervention,description,source_measurement_id:draft.measurement_id})}}><Plus size={15}/> Create PENDING order</button></div></div></div>}
 </>
}
