import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { Activity, ArrowRight, CheckCircle2, CircleAlert, Database, FileCog, Fingerprint, Gauge, MapPin, Settings2, ShieldCheck, Box } from 'lucide-react'
import { api } from '../services/api'
import { STATIC_DEMO } from '../services/staticDemo'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'

export function SettingsPage(){
 const qa=useQuery({queryKey:['qa-summary'],queryFn:api.qa});const summary=useQuery({queryKey:['maintenance-summary'],queryFn:api.maintenanceSummary});const models=useQuery({queryKey:['3d-models'],queryFn:api.model});const hotspots=useQuery({queryKey:['hotspots'],queryFn:api.hotspots});const nav=useNavigate()
 const q=qa.data;const s=summary.data;const tests=q?.qa||{}
 return <>
  <PageHeader eyebrow="SYSTEM CONFIGURATION & TRACEABILITY" title="Settings & calibration" description="Inspect validated source configuration, 3D assets and manual hotspot calibration status." action={<button className="button button-primary" onClick={()=>nav('/structural-3d')}><MapPin size={15}/>{STATIC_DEMO?' Open 3D model':' Calibrate on 3D model'}</button>}/>
  <div className="settings-callouts"><div><ShieldCheck size={19}/><span><b>RAW source is read-only</b><small>{STATIC_DEMO?'El historial validado permanece intacto. Las inspecciones, órdenes y evidencias nuevas se guardan en este navegador y no se comparten entre dispositivos.':'The workbook remains the evidence of record. New inspection data are appended to local SQLite and never written back to the workbook.'}</small></span></div><div><Activity size={19}/><span><b>Last condition is historical</b><small>No live telemetry or predictive model is connected to this application.</small></span></div></div>
  <div className="settings-grid"><section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">DATASET PROVENANCE</span><h2>Validated history</h2></div><Database size={17}/></div><div className="settings-kv"><div><span>Source workbook</span><b>DATOSCRUDOS/EH4000_historial_grietas.xlsx</b></div><div><span>Scope</span><b>EH4-01 · Tijeras y spindle · SD-01…SD-04</b></div><div><span>Period</span><b>{q?.dataset?.period_start||'—'} → {q?.dataset?.period_end||'—'}</b></div><div><span>Inspection dates</span><b>{q?.dataset?.inspections??'—'}</b></div><div><span>Expected / present rows</span><b>{q?.dataset?.expected_records??'—'} / {q?.dataset?.existing_records??'—'}</b></div><div><span>Completeness</span><b>{q?.dataset?.completeness_pct??'—'}%</b></div><div><span>NULL readings</span><b>{q?.dataset?.null_measurements??'—'} · preserved as N/I</b></div><div><span>Source integrity</span><b>{q?.validation?.source_unchanged?'RAW unchanged':'Hash verification not recorded'}</b></div></div></section>
   <section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">VALIDATED ENGINE SETTINGS</span><h2>Thresholds & tolerance</h2></div><Gauge size={17}/></div><div className="rule-info"><div><span>MEASUREMENT_TOLERANCE_MM</span><b>{q?.measurement_uncertainty?.tolerance_mm??10} mm</b><small>{q?.measurement_uncertainty?.purpose||'Interpretation of change between inspections'}</small></div><div><span>STRUCTURAL STATE</span><small>RAW L &lt; Caution → Normal · Caution ≤ L &lt; Danger → Alert · L ≥ Danger → Critical · NULL → N/I</small><em>Tolerance does not change structural state.</em></div></div><div className="threshold-settings">{['SD-01','SD-02','SD-03','SD-04'].map(p=><div key={p}><b>{p}</b><span>Caution <strong>{q?.points?.[p]?.caution_mm??'—'} mm</strong></span><span>Danger <strong>{q?.points?.[p]?.danger_mm??'—'} mm</strong></span></div>)}</div></section>
   <section className="panel settings-panel model-assets-settings"><div className="panel-heading"><div><span className="eyebrow">GEOMETRY SOURCE</span><h2>3D model assets</h2></div><Box size={18}/></div>{(models.data||[]).map((m:any)=><div className="model-asset-row" key={m.id}><div className="asset-type-icon"><Box size={19}/></div><div><b>{m.filename}</b><span>{m.format} · {m.mesh_count} mesh · {m.geometry_units}</span><small>{m.role} · {m.available?'loaded by web viewer':'file missing'}</small></div><span className={`asset-state ${m.available?'available':'unavailable'}`}>{m.available?'AVAILABLE':'MISSING'}</span></div>)}<div className="geometry-note"><b>Import evaluation</b><p>Suspension STL is a single technical mesh with no sub-part labels. The EH4000 I3D references external GIANTS “$data/” assets and a proprietary .shapes geometry bundle; the browser viewer uses the verifiable STL, and does not claim I3D conversion.</p><p>Source STL does not document units. Display uses a documented Z-up → Y-up transform and uniform fit scaling. Hotspot CAD coordinates are stored in the source-local frame.</p></div></section>
  <section className="panel settings-panel calibration-settings"><div className="panel-heading"><div><span className="eyebrow">HOTSPOT CALIBRATION</span><h2>Point positions</h2></div><Fingerprint size={17}/></div><p className="settings-explainer">Initial SD hotspots are provisionally aligned to the official drawing and STL source axes. A user can check placement visually on the mesh; this status records only a viewer check and is not engineering certification.</p><div className="calibration-list">{(hotspots.data||[]).map((h:any)=><div key={h.code}><span className="calibration-icon"><MapPin size={15}/></span><div><b>{h.code}</b><small>{h.calibration?h.calibration.confirmed?'Visually checked in viewer':'Provisional CAD position':'Not calibrated'}</small>{h.calibration&&<small>Source coordinates {h.calibration.x.toFixed(1)}, {h.calibration.y.toFixed(1)}, {h.calibration.z.toFixed(1)}</small>}</div><span className={`cal-status ${h.calibration_status.toLowerCase()}`}>{h.calibration_status.replaceAll('_',' ')}</span></div>)}</div><button className="button button-outline full-width" onClick={()=>nav('/structural-3d')}><MapPin size={15}/>{STATIC_DEMO?' Ver posiciones en 3D':' Open calibration mode'} <ArrowRight size={14}/></button></section>
   <section className="panel settings-panel test-results"><div className="panel-heading"><div><span className="eyebrow">QA GATE</span><h2>Source checks</h2></div><FileCog size={17}/></div><div className="test-summary-strip"><div><CheckCircle2 size={16}/><b>{tests.tests_pass??'—'}</b><span>passed</span></div><div><CircleAlert size={16}/><b>{tests.tests_warning??'—'}</b><span>warnings</span></div><div><CircleAlert size={16}/><b>{tests.tests_fail??'—'}</b><span>failed</span></div><span className="qa-classification">{tests.quality_classification||'—'}</span></div><div className="test-list">{(q?.tests||[]).map((t:any,i:number)=><div key={i}><span className={`test-indicator ${t.status.toLowerCase()}`}/><b>{t.test}</b><span>{t.detail}</span><em>{t.status}</em></div>)}</div></section></div>
  <div className="settings-footer"><Settings2 size={15}/><span>Los registros de esta instalación se guardan en la base de datos configurada por el administrador del sitio.</span></div>
 </>
}
