import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import { assetUrl, STATIC_DEMO } from '../services/staticDemo'
import { stateSlug } from '../types'
import { useUI } from '../state'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge, PriorityBadge } from '../components/StatusBadge'
import { SuspensionViewer } from '../components/SuspensionViewer'
import { Crosshair, Check, MapPin, RotateCcw, SlidersHorizontal, AlertCircle, ArrowRight } from 'lucide-react'

export function StructuralPage(){
 const id=useUI(s=>s.selectedInspectionId);const selected=useUI(s=>s.selectedPoint);const setSelected=useUI(s=>s.setPoint);const notify=useUI(s=>s.notify);const qc=useQueryClient();const nav=useNavigate()
 const [calibrating,setCalibrating]=useState(false)
 const points=useQuery({queryKey:['points',id],queryFn:()=>api.points(id)})
 const snap=useQuery({queryKey:['overview',id],queryFn:()=>api.overview(id)})
 const calibrations=useQuery({queryKey:['hotspots'],queryFn:api.hotspots})
 const current=points.data?.find(p=>p.code===selected)||points.data?.[0]
 const save=async(code:string,pos:{x:number;y:number;z:number;nx:number;ny:number;nz:number})=>{try{await api.saveHotspot(code,{...pos,confirmed:false,calibrated_by:'viewer user (identity not configured)'});await qc.invalidateQueries({queryKey:['points']});await qc.invalidateQueries({queryKey:['hotspots']});notify('success',`${code}: posición guardada como no verificada.`);setCalibrating(false)}catch(e){notify('error',String(e))}}
 const confirm=async()=>{if(!current?.calibration)return;try{await api.saveHotspot(current.code,{x:current.calibration.x,y:current.calibration.y,z:current.calibration.z,nx:current.calibration.normal[0],ny:current.calibration.normal[1],nz:current.calibration.normal[2],confirmed:true,calibrated_by:'viewer user (identity not configured)'});await qc.invalidateQueries({queryKey:['points']});await qc.invalidateQueries({queryKey:['hotspots']});notify('success',`${current.code} marcado como verificado.`)}catch(e){notify('error',String(e))}}
 const hotspotByCode=new Map((calibrations.data||[]).map(x=>[x.code,x]))
 const calibratedPoints=(points.data||[]).map(p=>({...p,calibration:(hotspotByCode.get(p.code)?.calibration||p.calibration)||null}))
 return <>
  <PageHeader eyebrow="STRUCTURAL DIGITAL TWIN" title="Front suspension" description="Hotspots provisionales alineados con el plano SD; el visor muestra estado y ubicación, no aprobación de mantenimiento" action={<button className="button button-outline" onClick={()=>nav('/settings')}><SlidersHorizontal size={15}/> Calibration settings</button>}/>
  <div className="model-meta-strip"><div><span>ASSET</span><b>EH4000 · EH4-01</b></div><div><span>INSPECTION</span><b>{snap.data?.date||'—'} · {snap.data?.hours?.toLocaleString('es-CO')} h</b></div><div><span>GEOMETRY</span><b>Suspension STL · single mesh</b></div><div><span>CAD LOCATION CHECK</span><b>{calibratedPoints.filter(p=>p.calibration?.confirmed).length} / 4 visually checked</b></div><div className="meta-status">{snap.data?.historical_only&&<em>HISTORICAL CONDITION</em>}</div></div>
  <div className="structural-workspace"><section className="panel large-viewer-panel"><div className="panel-heading"><div><span className="eyebrow">3D INSPECTION VIEW</span><h2>Suspension front assembly</h2></div><div className="viewer-limits"><span><i className="legend-caution"/>Caution</span><span><i className="legend-danger"/>Danger</span></div></div><SuspensionViewer points={calibratedPoints as any} selectedPoint={selected} onSelect={setSelected} calibratingPoint={calibrating?selected:null} onCalibrationSave={STATIC_DEMO?undefined:save}/><div className="model-bottom-controls"><div>{!STATIC_DEMO&&<button className={`button ${calibrating?'button-warning':'button-outline'}`} onClick={()=>setCalibrating(v=>!v)}><Crosshair size={15}/>{calibrating?'Cancel calibration':`Calibrate ${selected}`}</button>}<small>{calibrating?'Click a physical location on the STL mesh.':'Use the official SD drawing as a location reference; this check does not approve a maintenance recommendation.'}</small></div><div className="surface-patch-note"><i/>Expanded color footprint on the STL identifies SD point and state; it is not a physical crack dimension.</div><button className="button button-ghost" onClick={()=>nav('/settings')}><RotateCcw size={15}/> Manage hotspots</button></div></section>
   <aside className="panel model-point-panel"><div className="panel-heading"><div><span className="eyebrow">INSPECTION POINTS</span><h2>Front suspension</h2></div><span className="point-count">04</span></div><div className="point-list">{calibratedPoints.map(p=><button key={p.code} className={`model-point-row ${selected===p.code?'selected':''}`} onClick={()=>setSelected(p.code)}><div className="point-row-state"><i className={`state-dot-${stateSlug(p.structural_state)}`}/></div><div className="point-row-copy"><b>{p.code}</b><span>{p.description}</span><div><StatusBadge state={p.structural_state}/><small>{p.calibration?.confirmed?'Visually checked in viewer':p.calibration?'Provisional CAD position':'Not calibrated'}</small></div></div><div className="point-row-length"><strong>{p.length_mm===null?'—':p.length_mm}</strong><span>mm</span><PriorityBadge priority={p.maintenance_priority??null}/></div></button>)}</div>
    {current&&<div className="model-selected-detail"><div className="panel-heading"><div><span className="eyebrow">SELECTED POINT</span><h3>{current.code}</h3></div><StatusBadge state={current.structural_state}/></div><p>{current.description}</p><div className="three-col-values"><div><span>RAW LENGTH</span><b>{current.length_mm===null?'N/I':`${current.length_mm} mm`}</b></div><div><span>CAUTION</span><b>{current.caution_mm} mm</b></div><div><span>DANGER</span><b>{current.danger_mm} mm</b></div></div><div className="detail-metrics-grid"><div><span>CAUTION UTILIZATION</span><b>{current.length_mm===null?'N/I':`${(current.length_mm/current.caution_mm!*100).toFixed(0)}%`}</b></div><div><span>SEVERITY / DANGER</span><b>{current.length_mm===null?'N/I':`${(current.length_mm/current.danger_mm!*100).toFixed(0)}%`}</b></div><div><span>MARGIN TO DANGER</span><b>{current.length_mm===null?'N/I':`${(current.danger_mm!-current.length_mm).toFixed(1)} mm`}</b></div><div><span>ΔL RAW / EFFECTIVE</span><b>{current.delta_l_raw===null||current.delta_l_raw===undefined?'—':`${current.delta_l_raw} / ${current.delta_l_effective} mm`}</b></div><div><span>RAW RATE</span><b>{current.raw_growth_rate===null||current.raw_growth_rate===undefined?'—':`${current.raw_growth_rate.toFixed(2)} mm / 1000 h`}</b></div><div><span>CHANGE CLASS</span><b>{(current.change_class||'—').replaceAll('_',' ')}</b></div></div>{current.gap_spanning_change&&<div className="caution-callout"><AlertCircle size={14}/><span>GAP SPANNING CHANGE · {current.delta_l_bridged_raw} mm desde {current.bridged_from_date}. Intervalo incompleto; no es una tasa ordinaria.</span></div>}<div className="action-focus"><WrenchIcon/><div><small>RECOMMENDATION · {current.maintenance_priority||'BASELINE'}</small><b>{(current.maintenance_action||'—').replaceAll('_',' ')}</b></div><button title="View recommendation" onClick={()=>nav('/maintenance')}><ArrowRight size={15}/></button></div>
    {current.calibration&&<div className="calibrated-coords"><MapPin size={15}/><span>CAD coordinates: {current.calibration.x.toFixed(1)}, {current.calibration.y.toFixed(1)}, {current.calibration.z.toFixed(1)}<small>{current.calibration.confirmed?'Visually checked in viewer; not engineering certification':'Provisional match to official SD drawing · visual check on STL; no engineering approval is implied'}</small></span>{!STATIC_DEMO&&!current.calibration.confirmed&&<button onClick={confirm}><Check size={14}/>Mark visually checked</button>}</div>}
    <div className="caution-callout"><AlertCircle size={15}/><span>The expanded surface footprint is a visual locator for the SD point and its state; it does not define the inspected physical area or crack geometry.</span></div></div>}
    <details className="official-scheme"><summary><span><MapPin size={14}/> Official inspection form · SD layout</span><small>Reference for provisional CAD mapping</small></summary><a href={assetUrl('schemes/sd_inspection_reference.png')} target="_blank" rel="noreferrer"><img src={assetUrl('schemes/sd_inspection_reference.png')} alt="Official EH4000 inspection form showing the SD-01, SD-02, SD-03 and SD-04 inspection regions"/></a><p>Source: DATOSCRUDOS/EH4000_formato_inspeccion.docx. The provisional hotspot mapping follows the official SD drawing. A visual check in this viewer is not an engineering certification or maintenance approval.</p></details>
    <div className="point-panel-footer"><small>Raw measurement for inspection {snap.data?.date} · no length interpolation.</small></div>
   </aside></div>
 </>
}
function WrenchIcon(){return <Crosshair size={15}/>}
